name: GuideFrame Tests
# Trigger the workflow on push
on: [push]
# All jobs in the workflow
jobs:
  selenium-function-test:
    runs-on: ubuntu-latest
    # steps to run
    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4
    # Set up environment
    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          ffmpeg \
          xvfb \
          chromium-driver \
          chromium-browser
          pip install selenium \
          ffmpeg-python \
          mutagen \
          gTTS
    # Run the main automation script
    - name: Run Automation Test with Virtual Display
      run: |
        # Start virtual display
        export DISPLAY=:99
        nohup Xvfb :99 -screen 0 1920x1080x24 &

        export PYTHONPATH=$GITHUB_WORKSPACE:$PYTHONPATH
        
        # Run the Selenium script
        python3 -m selenium_demos.selenium_automation_tests github
